<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\Versions.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <!--PackageReference Include="MetaDslx.BuildTools" Version="$(MetaDslxVersion)" PrivateAssets="All" /-->
    <PackageReference Include="MetaDslx.CodeAnalysis" Version="$(MetaDslxVersion)" />
  </ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="**\*.mxm" />
		<AdditionalFiles Include="**\*.mxl" />
		<AdditionalFiles Include="**\*.mxs" />
		<AdditionalFiles Include="**\*.mxg" />
	</ItemGroup>
	
    <Target Name="MetaDslx" BeforeTargets="BeforeBuild" Inputs="**\*.mxm;**\*.mxl;**\*.mxs;**\*.mxg" Outputs="**\*.cs">
	    <Exec Command="dotnet metadslx" />
    </Target>	
</Project>
